name: helm-validate-poc
on:
  pull_request:

jobs:
  helm-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR (head)
        uses: actions/checkout@v4

      - name: Checkout base branch (baseline)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}
          path: base

      - name: Create Kind cluster
        uses: helm/kind-action@v1

      - name: Setup Helm (latest)
        uses: azure/setup-helm@v4.3.0
        with:
          version: latest

      - name: Install Helm Diff
        run: helm plugin install https://github.com/databus23/helm-diff

      - name: Lint chart
        run: helm lint charts/my-chart -f charts/my-chart/values.yaml --strict

      - name: Server-side dry-run validation
        run: |
          helm template my-release charts/my-chart -f charts/my-chart/values.yaml \
          | kubectl apply --dry-run=server -f -

      - name: Baseline install from base branch
        run: |
          kubectl create ns poc || true
          helm dependency build base/charts/my-chart || true
          helm install my-release base/charts/my-chart -n poc \
            -f base/charts/my-chart/values.yaml --wait --timeout 5m

      - name: Helm diff (plan)
        id: plan
        shell: bash
        run: |
          helm dependency build charts/my-chart || true
          set +e
          helm diff upgrade my-release charts/my-chart \
            -n poc -f charts/my-chart/values.yaml --detailed-exitcode \
            | tee /tmp/helm.diff
          ec=${PIPESTATUS[0]}
          # Build markdown comment
          {
            echo "### Helm plan (Kind POC)"
            if [ $ec -eq 0 ]; then
              echo "✅ No changes."
            elif [ $ec -eq 2 ]; then
              echo "⚠️ Changes detected."
              echo ""
              echo "<details><summary>Show diff</summary>"
              echo
              echo '```diff'
              # GitHub comment max ~65k; keep it safe
              head -c 60000 /tmp/helm.diff
              echo
              echo '```'
              echo "</details>"
            else
              echo "❌ \`helm diff\` failed with exit code $ec"
            fi
          } > /tmp/comment.md
          echo "exitcode=$ec" >> $GITHUB_OUTPUT

      - name: Post sticky PR comment
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: /tmp/comment.md
