name: helm-validate-poc
on:
  pull_request:

jobs:
  helm-validate:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout PR (head)
        uses: actions/checkout@v4

      - name: Checkout base branch (baseline)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}
          path: base

      - name: Create Kind cluster
        uses: helm/kind-action@v1

      - name: Setup Helm (latest)
        uses: azure/setup-helm@v4.3.0
        with:
          version: latest

      - name: Install Helm Diff
        run: helm plugin install https://github.com/databus23/helm-diff

      - name: Lint chart
        run: helm lint myapp -f myapp/values.yaml --strict

      - name: Server-side dry-run validation
        run: |
          helm template my-release myapp -f myapp/values.yaml \
          | kubectl apply --dry-run=server -f -

      - name: Baseline install from base branch
        run: |
          kubectl create ns poc || true
          helm install my-release base/myapp -n poc \
            -f base/myapp/values.yaml --wait --timeout 5m

      - name: Helm diff (plan)
        id: plan
        shell: bash
        run: |
          helm diff upgrade my-release myapp \
            -n poc -f myapp/values.yaml --allow-unreleased --collor \
            | tee /tmp/helm.diff\
            | sed 's/\x1b\[[0-9;]*m//g' > helm-diff-plain.md

          # If no changes, log a message
          if [ ! -s helm-diff-plain.md ]; then
            echo "✅ No Helm changes detected."
          else
            echo "```diff" > helm-diff.md
            cat helm-diff-plain.md >> helm-diff.md
            echo "```" >> helm-diff.md
          fi

      - name: Post sticky PR comment
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: helm-diff.md
